### ISSUE TITLE
Database hosten op azure

### ISSUE THREAD

**Issue by Levi--G** [Levi--G/CA-Paperless-Office-LHS#20]
Database aanmaken op azure en configuratiefile aanmaken in config folder als placeholder voor database naam en wachtwoorden.

**Comment by Levi--G** [comment]
Ik heb aan mijn vader gevraagt om een database en blob storage. Ik heb beide gekregen. Ik zal morgen eens zien voor zo'n configuratie file voor de db en storage.

**Comment by Levi--G** [comment]
Template file aangemaakt in 396b769b2bfdfb50bdf9aab15ee84b9a17ff7495

**Comment by HanneloreP** [comment]
OK.
