### ISSUE TITLE
Nodejs module voor database interface aanmaken voor login table

### ISSUE THREAD

**Issue by Levi--G** [Levi--G/CA-Paperless-Office-LHS#21]

**Comment by Levi--G** [comment]
Login en Register functies in 36d9b174ddaf8213ef641bcb34f9b5c043ddfbe2
Master gemerged in feature (voor pull request) in b9a4216c7dbd0e146fde882a7b4de1feb4fb3a80
Kan iemand deze commit nakijken en goedkeuren dan maak ik een pull request

**Comment by HanneloreP** [comment]
OK.
