### ISSUE TITLE
Status login gebruiker weergeven in navbar

### ISSUE THREAD

**Issue by Levi--G** [Levi--G/CA-Paperless-Office-LHS#28]

**Comment by HanneloreP** [comment]
Working in 423c21e773f42a1708e08f4da5b7a9d8bd7cfd4a
Only have to add 'close modal'

**Comment by HanneloreP** [comment]
Completed in 39599c6ea399c2430a7e3537437f9c56c33b7693

**Comment by Levi--G** [comment]
OK
