### ISSUE TITLE
Design en content homepage

### ISSUE THREAD

**Issue by Levi--G** [Levi--G/CA-Paperless-Office-LHS#30]
- [x] Navbar
- [x] Summary with images
- [x] Content paragraphs

Design template: http://getbootstrap.com/examples/carousel/

**Comment by HanneloreP** [comment]
In Progress on feature-homepage branch (4e99305ce2991fe67a5cd4cfd448005b20a74477)

**Comment by HanneloreP** [comment]
Completed in 98a20e331dbea9c4153fff7a2876a3abf94f8be4
=> Definitive text to be added

**Comment by Levi--G** [comment]
OK, maak maar een pull request
