### ISSUE TITLE
Homepage doesn't link to the controller

### ISSUE THREAD

**Issue by Levi--G** [Levi--G/CA-Paperless-Office-LHS#32]
controller.js isn't included in the homepage head

**Comment by HanneloreP** [comment]
Completed in 148ee0e18396e5117b95259490fd5e42c517b226

**Comment by Levi--G** [comment]
Vergeten "/" toe te voegen?

**Comment by HanneloreP** [comment]
Completed in 902bddec5ade1b7ee82d70e7f59372002ce7116d

**Comment by Levi--G** [comment]
OK
