### ISSUE TITLE
Design detailview

### ISSUE THREAD

**Issue by HanneloreP** [Levi--G/CA-Paperless-Office-LHS#54]
Apart pagina of modal?

**Comment by SverreO** [comment]
Ik heb apparte pagina

**Comment by SverreO** [comment]
Hoe gaan we de data doorgeven aan de site?

**Comment by SverreO** [comment]
Beslist via url variable

**Comment by SverreO** [comment]
data doorgeven gedaan in 9b774dc21c574927e3e114595a4fb7b4e0cedb6e
